### ISSUE TITLE
Error when Main Application uses Eureka

### ISSUE THREAD

**Issue by syifarahmat** [hank-cp/sbp#5] opened 2020-05-04 12:52 UTC
How to solve the following problem ??

My main application use eureka client
If the plugin does not use eureka configuration, it will error.
But not to the contrary, I have to force the plugin to use eureka config.

SS:
I have to force the plugin to use eureka config. its OK
![image](https://user-images.githubusercontent.com/11779955/80967134-10417d80-8e40-11ea-9ecd-c9874f935b60.png)

But if set to false is Fails
![image](https://user-images.githubusercontent.com/11779955/80967535-b7261980-8e40-11ea-9ef6-1bd900ec8d0e.png)
Result :
![image](https://user-images.githubusercontent.com/11779955/80967595-d58c1500-8e40-11ea-95e4-8dcb7678d8e4.png)

**Comment by hank-cp** [comment] 2020-05-05 02:09
Plugin shouldn't have been register to eureka as one of the hosts. Anything plugin needs from external, should be injected by the main app, who is in charge of interacting with other service throw Spring Cloud stuffs.

Could you please post the complete logs/configs or create a repo to reproduce this?

**Comment by syifarahmat** [comment] 2020-05-08 07:44
Thanks.... this is my config core/main app with eureka and & plugin wihtaut eureka
https://github.com/syifarahmat/pluginnable/tree/master

**Comment by hank-cp** [comment] 2020-05-08 17:20
Hi, see your repo. I am sorry that I cannot figure where the problem is with just some few configuration files. 

If you feel difficult to create a runnable project to reproduce this issue, could you at least provide a complete startup log instead?

**Comment by syifarahmat** [comment] 2020-05-09 03:43
I have reuploaded the project simply.
https://github.com/syifarahmat/pluginnable
The Jhipster registry and its configuration are in the release folder. you can see the file.cmd how do I load the config.
My main obstacle is why I have to force the eureka config set for each plugin ... ??
![image](https://user-images.githubusercontent.com/11779955/81463214-f27a6c80-91e1-11ea-9e07-1bfbe2aaf38a.png)

Thanks a lot.

**Comment by hank-cp** [comment] 2020-05-12 06:43
Looks like your are referring eureka libs from your dependencies tree. 

 Basically Spring Cloud stuffs should exist in any classpath, otherwise they will trigger Spring Boot auto configuration, even though you do not mean to play with them.

Try close eureka explictly by adding follow to `/plugins/pluginone/src/main/resources/application.yml`:
```
  eureka:
    instance:
      hostname: localhost
    client:
      registerWithEureka: false
      fetchRegistry: false
```

**Comment by syifarahmat** [comment] 2020-05-13 03:17
Thanks..... 🙏🙏🙏
I will try...

**Comment by hank-cp** [comment] 2020-05-13 03:36
u r welcome. I am closing this issue.

**Closed by hank-cp** 2020-05-13 03:36 UTC
